version: '3.8'

services:
  app:
    container_name: url-shortener
    build: .
    restart: always
    ports:
      - 8282:8282
    depends_on:
      - pg_db
    environment:
      - APP_IP=0.0.0.0
      - APP_PORT=8282
      - DB_CONNECTION_STRING=postgres://postgres:password@pg_db:5432/postgres?sslmode=disable

  pg_db:
    image: postgres:13.1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
