// Package routeropenapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package routeropenapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ApiStatistics defines model for ApiStatistics.
type ApiStatistics struct {
	Count  *int    `json:"count,omitempty"`
	Ip     *string `json:"ip,omitempty"`
	Long   *string `json:"long,omitempty"`
	Short  *string `json:"short,omitempty"`
	Viewed *string `json:"viewed,omitempty"`
}

// ApiURL defines model for ApiURL.
type ApiURL struct {
	Admin   *string `json:"admin,omitempty"`
	Created *string `json:"created,omitempty"`
	Id      *int    `json:"id,omitempty"`
	Long    *string `json:"long,omitempty"`
	Short   *string `json:"short,omitempty"`
}

// PostAJSONBody defines parameters for PostA.
type PostAJSONBody = ApiStatistics

// PostSCreateJSONBody defines parameters for PostSCreate.
type PostSCreateJSONBody = ApiURL

// PostAJSONRequestBody defines body for PostA for application/json ContentType.
type PostAJSONRequestBody = PostAJSONBody

// PostSCreateJSONRequestBody defines body for PostSCreate for application/json ContentType.
type PostSCreateJSONRequestBody = PostSCreateJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Index page with form
	// (GET /)
	Get(w http.ResponseWriter, r *http.Request)
	// Shows URL statistics
	// (POST /a)
	PostA(w http.ResponseWriter, r *http.Request)
	// Admin page
	// (GET /a/{admin})
	GetAAdmin(w http.ResponseWriter, r *http.Request, admin string)
	// Error page
	// (GET /err)
	GetErr(w http.ResponseWriter, r *http.Request)
	// Create URL
	// (POST /s/create)
	PostSCreate(w http.ResponseWriter, r *http.Request)
	// Redirect to long original URL
	// (GET /s/{short})
	GetSShort(w http.ResponseWriter, r *http.Request, short string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.HandlerFunc) http.HandlerFunc

// Get operation middleware
func (siw *ServerInterfaceWrapper) Get(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Get(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostA operation middleware
func (siw *ServerInterfaceWrapper) PostA(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostA(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetAAdmin operation middleware
func (siw *ServerInterfaceWrapper) GetAAdmin(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "admin" -------------
	var admin string

	err = runtime.BindStyledParameter("simple", false, "admin", chi.URLParam(r, "admin"), &admin)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "admin", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAAdmin(w, r, admin)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetErr operation middleware
func (siw *ServerInterfaceWrapper) GetErr(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetErr(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// PostSCreate operation middleware
func (siw *ServerInterfaceWrapper) PostSCreate(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSCreate(w, r)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

// GetSShort operation middleware
func (siw *ServerInterfaceWrapper) GetSShort(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "short" -------------
	var short string

	err = runtime.BindStyledParameter("simple", false, "short", chi.URLParam(r, "short"), &short)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "short", Err: err})
		return
	}

	var handler = func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSShort(w, r, short)
	}

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.Get)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/a", wrapper.PostA)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/a/{admin}", wrapper.GetAAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/err", wrapper.GetErr)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/s/create", wrapper.PostSCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/s/{short}", wrapper.GetSShort)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWTW/bOBD9K8TsHrWRt24vurlFkAZJkcBKDkWbAyNNbBYSyQ5HSQxD/70YSoA/IrVI",
	"AxctejFIDmc4fI/vWWsoXO2dRcsBsjWEYom1jsOZNzlrNoFNERc8OY/EBuOscI1lGfDKI2RgLOMCCdoE",
	"jN9aD0zGLmS5cnYxGAhLRzwYuTf4gOVAqG0TafB6fv60M13Wxg6WKwg1D9ZLwJTDl3l2121sztg7J8ES",
	"Q0HGs3EWMpgf51dqdnkKCbDhStJyU/sKVUC6NwX2wXuk0GX8fzQ5mshxzqPV3kAG07iUgNe8jBdO5WeB",
	"/PS8U1vio/J6gerB8FLdOaoh1iItW05LyOAEGRIgDN7Z0EH4ajLpOLaMPcv4yOmS6woy21RVm+yddHEG",
	"CeCjlsuEvQT43Ewm00ImcYTd/NaVq27+0TWk3l99OFeS1UXTTbhf2OSDIPym63G3DSGOrK4inkgKiRzF",
	"7aGpa02rMVBkS6rjY3JhAMl86R6Cup6fq7ARxT6Sly7wLGL5tcHAb1252oNRe1+ZImakX4KzG83J6F/C",
	"O8jgn3QjyrRXZLorx/jGdjuUckpA6xswJC+dqcH2h+wesK2LM3m9r4fIutWl6qGClxA6yE1HaLqObtCO",
	"KmQm4fgYhnQxi+GoNdI1MlKA7NN+jegEqnCl1BDridKEBKyuReK6L7LLSrKF8L6F3PyBejwoxVs0RWKR",
	"aJTSY8kfpfSY6K9yuy00InIh7f4Fx63uXYyLngYNLu/ih7M5Ofh38reRfn6BsW0x0XO3jl4zbmdzLA1h",
	"wYqdki8X5cgsjBwzROcJcp7Hz5gXOlzoi/y8w00n02drUP2nqL/vwan4PrDxeXTZHXwNiROk0N603wIA",
	"AP//rJnP5WMLAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
